config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'reports#index'

  devise_for :users
  authenticated :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users
  resources :teams
  resources :categories

  get 'stats' => 'stats#index'
  get 'stats/user'     => 'stats#user'
  get 'stats/team'     => 'stats#team'
  get 'stats/category' => 'stats#category'
  get 'stats/all'      => 'stats#all'

  post 'stat_reports/user'     => 'stat_reports#user'
  post 'stat_reports/team'     => 'stat_reports#team'
  post 'stat_reports/category' => 'stat_reports#category'
  post 'stat_reports/all'      => 'stat_reports#all'

  post 'exports/stat' => 'exports#stat'

  resources :reports
  get  'reports/:id/sign'   => 'reports#sign',   :as => :sign_report
  get  'reports/:id/export' => 'reports#export', :as => :timesheet_export
  post 'reports/search'     => 'reports#search'

  match '*path', to: 'application#not_found', via: :all
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable

  belongs_to :team, optional: true
  has_many :reports, dependent: :destroy
  has_many :hours, through: :reports

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            email_pattern: true
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name,  presence: true, length: { minimum: 2 }
  validates :password, confirmation: true, unless: -> { password.blank? }
  validates :rate, presence: true

  def full_name
    ([first_name, last_name] - ['']).compact.join(' ')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controller
class UsersController < ApplicationController
  before_action :authorize_admin, except: :show
  before_action :set_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show
    if params[:id].to_i == current_user.id || current_user.admin
      @user = User.find(params[:id])
    else
      redirect_to root_path, alert: 'Access denied!'
    end
  end

  def new
    @user = User.new
    @teams = Team.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      CreateNewTimesheetsWorker.perform_async(@user.id)
      redirect_to @user, notice: 'User has been successfully created!'
    else
      render 'new'
    end
  end

  def edit
    @teams = Team.all
  end

  def update
    if @user.update(user_params)
      redirect_back fallback_location: users_path, notice: 'User has been successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: 'User has been successfully deleted!'
    else
      render action: 'edit'
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation,
                  :first_name, :last_name, :team_id, :rate, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.haml
.container
  .row
    .col-md-4
      %h3
        %b Edit user
      %hr
      = simple_form_for @user do |f|
        = f.error_notification
        .form-group
          = f.input :email
          = f.input :first_name
          = f.input :last_name
          = f.input :team_id, :as => :select, collection: @teams, prompt: "Select team"
          = f.input :rate, as: :integer, input_html: { min: "0", max: "200", step: "any" }
          %div{:align => "right"}
            %b Admin
            = f.input_field :admin, as: :boolean, boolean_style: :inline
        .form-actions
          = link_to "Go back", :back, class: "btn btn-primary"
          = link_to "Delete", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"
          = f.button :submit, "Update", class: "btn btn-success"

app/views/users/index.html.haml
.container
  .row
    .col-md-8
      %h2
        %b Users
      %table.table
        %tr
          %th Email
          %th First Name
          %th Last Name
          %th Team
          %th Admin
        - @users.each do |user|
          %tr
            %td= link_to user.email, user_path(user)
            %td= user.first_name
            %td= user.last_name
            %td= user.team ? user.team.name : "No team assigned"
            %td= user.admin ? "Yes" : "No"
      %hr
      %div{:align => "right"}
        = link_to "Add user", new_user_path, class: "btn btn-success"

app/views/users/new.html.haml
.container
  .row
    .col-md-4
      %h3
        %b Add user
      %hr
      = simple_form_for @user do |f|
        = f.error_notification
        .form-group
          = f.input :email
          = f.input :first_name
          = f.input :last_name
          = f.input :rate, as: :integer, input_html: { min: "0", max: "200", step: "any" }
          = f.input :password, hint: false, error_html: { id: "password_error"}
          = f.input :password_confirmation, label: false
          = f.input :team_id, :as => :select, collection: @teams, prompt: "Select team"
          %div{ align: "right" }
            %b Admin
            = f.input_field :admin, as: :boolean, boolean_style: :inline
        .form-actions
          = link_to "Go back", :back, class: "btn btn-primary"
          = f.button :submit, "Create", class: "btn btn-success"

app/views/users/show.html.haml
.container
  .row
    .col-md-4
      %h3
        %b= "#{@user.full_name} (#{@user.email})"
      %hr
      %div{:align => "right"}
        = "Member since #{l @user.created_at.to_date, format: :short}"
        %hr
        = "Member of "
        - if @user.team && current_user.admin
          = link_to @user.team.name, team_path(@user.team)
        - elsif @user.team
          = @user.team.name
        - elsif @user.team.nil?
          = "no one"
        = " team"
        %hr
        = "Hourly rate: #{@user.rate}"
        %hr
        = link_to "Go back", :back, class: "btn btn-primary"
        = link_to "Delete", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" if current_user.admin
        = link_to "Edit", edit_user_path, class: "btn btn-success" if current_user.admin