config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'reports#index'

  devise_for :users
  authenticated :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users
  resources :teams
  resources :categories

  get 'stats' => 'stats#index'
  get 'stats/user'     => 'stats#user'
  get 'stats/team'     => 'stats#team'
  get 'stats/category' => 'stats#category'
  get 'stats/all'      => 'stats#all'

  post 'stat_reports/user'     => 'stat_reports#user'
  post 'stat_reports/team'     => 'stat_reports#team'
  post 'stat_reports/category' => 'stat_reports#category'
  post 'stat_reports/all'      => 'stat_reports#all'

  post 'exports/stat' => 'exports#stat'

  resources :reports
  get  'reports/:id/sign'   => 'reports#sign',   :as => :sign_report
  get  'reports/:id/export' => 'reports#export', :as => :timesheet_export
  post 'reports/search'     => 'reports#search'

  match '*path', to: 'application#not_found', via: :all
end

app/controllers/stats_controller.rb
# frozen_string_literal: true

# Stats controller
class StatsController < ApplicationController
  before_action :authorize_admin
  before_action :set_stat, except: [:index]

  def index;    end

  def user;     end

  def team;     end

  def category; end

  def all;      end

  private

  def set_stat
    @users      = User.all
    @teams      = Team.all
    @categories = Category.all
  end
end

app/views/stats/_body.html.haml
= label_tag(:date, "Date: ")
= select_tag "date", options_for_select([["Last week", "last_week"], ["Last month", "last_month"], ["Last year", "last_year"]]),
 class: "form-control", prompt: "Select a date"
%br/
= "OR select custom date"
%br/
%br/
= label_tag(:date_custom, "Custom date: ")
#datetimepicker1.input-group.date
  = text_field_tag(:date_custom, nil, class: "form-control")
  %span.input-group-addon
    %span.glyphicon.glyphicon-calendar
:javascript
  $(function () {
      $("#datetimepicker1").datepicker({
       todayHighlight: true,
       toggleActive: true
      });
  });


%hr
%div{:align => "right"}
  = link_to "Go back", :back, class: "btn btn-primary"
  = submit_tag("Generate stats", class: "btn btn-success")

app/views/stats/all.html.haml
.container
  .row
    .col-md-5
      %p.lead= "All users, teams, categories over a specified time period"
      %hr
      = form_tag(stat_reports_all_path, method: "post") do
        .form-group
          = hidden_field_tag "all"
          = render partial: "body"

app/views/stats/category.html.haml
.container
  .row
    .col-md-5
      %p.lead= "Single category stats for a specific period of time"
      %hr
      = form_tag(stat_reports_category_path, method: "post") do
        .form-group
          = label_tag(:category_id, "Category: ")
          = select_tag "category_id", options_from_collection_for_select(@categories, "id", "name"), class: "form-control"
          %br/
          = render partial: "body"

app/views/stats/index.html.haml
%h2
  %b Stats
%table.table
  %tr
    %td= link_to "Single user over a specified time period", stats_user_path
  %tr
    %td= link_to "Single team over a specified time period", stats_team_path
  %tr
    %td= link_to "Single category over a specified time period", stats_category_path
  %tr
    %td= link_to "All users over a specified time period", stats_all_path

app/views/stats/team.html.haml
.container
  .row
    .col-md-5
      %p.lead= "Single team over a specified time period"
      %hr
      = form_tag(stat_reports_team_path, method: "post") do
        .form-group
          = label_tag(:team_id, "Team: ")
          = select_tag "team_id", options_from_collection_for_select(@teams, "id", "name"), class: "form-control"
          %br/
          = render partial: "body"

app/views/stats/user.html.haml
.container
  .row
    .col-md-5
      %p.lead= "Single user over a specific time period"
      %hr
      = form_tag(stat_reports_user_path, method: "post") do
        .form-group
          = label_tag(:user_id, "User: ")
          = select_tag "user_id", options_from_collection_for_select(@users, "id", "full_name"), class: "form-control"
          %br/
          = render partial: "body"