config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'reports#index'

  devise_for :users
  authenticated :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users
  resources :teams
  resources :categories

  get 'stats' => 'stats#index'
  get 'stats/user'     => 'stats#user'
  get 'stats/team'     => 'stats#team'
  get 'stats/category' => 'stats#category'
  get 'stats/all'      => 'stats#all'

  post 'stat_reports/user'     => 'stat_reports#user'
  post 'stat_reports/team'     => 'stat_reports#team'
  post 'stat_reports/category' => 'stat_reports#category'
  post 'stat_reports/all'      => 'stat_reports#all'

  post 'exports/stat' => 'exports#stat'

  resources :reports
  get  'reports/:id/sign'   => 'reports#sign',   :as => :sign_report
  get  'reports/:id/export' => 'reports#export', :as => :timesheet_export
  post 'reports/search'     => 'reports#search'

  match '*path', to: 'application#not_found', via: :all
end

app/models/report.rb
# frozen_string_literal: true

# Report model
class Report < ApplicationRecord
  belongs_to :user
  has_many :hours, dependent: :delete_all
  accepts_nested_attributes_for :hours
  has_many :categories, through: :hours

  # rubocop:disable Rails/RedundantPresenceValidationOnBelongsTo
  validates :user, presence: true, on: %i[create update]
  # rubocop:enable Rails/RedundantPresenceValidationOnBelongsTo
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# Reports controller
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show update sign export]

  def index
    cr = current_user.reports
    path = cr.any? ? report_path(cr.last) : new_report_path
    redirect_to path
  end

  def new
    @report = Report.new(created_at: Time.zone.now, week_id: current_week)
    @report.categories = Category.all
    @total_hours = Date::DAYNAMES.to_h { |weekday| [weekday.downcase, 0] }

    week_begin_and_end(true)
    @previous = current_user.reports.last
  end

  def show
    @hours = @report.hours
                    .joins(:category)
                    .select('hours.*, categories.name as category_name')
    @total_hours = Date::DAYNAMES.to_h { |weekday| [weekday.downcase, 0] }

    @previous = current_user.reports.where(['id < ?', @report.id]).last
    @next     = current_user.reports.where(['id > ?', @report.id]).first
    week_begin_and_end

    render 'locked' if @report.timesheet_locked
  end

  def search
    if params[:date_custom] != ''
      reports = ReportService.search(current_user, params)
      if reports.any?
        redirect_to report_path(reports.first)
      else
        message = 'No reports have been found for a specified period!'
        redirect_back fallback_location: reports_path, alert: message
      end
    else
      redirect_back fallback_location: reports_path, alert: 'No input data has been received!'
    end
  end

  def create
    cw = current_week
    @report = current_user.reports.build(report_params.merge(week_id: cw))
    if @report.save
      message = 'Report has been successfully created!'
      redirect_to report_path(@report), notice: message
    else
      render 'new'
    end
  end

  def update
    if @report.update(report_params)
      @report.update(signed: true) if @report.signed == false
      if params[:commit] == 'Export'
        week_begin_and_end
        render xlsx: 'export', template: 'exports/timesheet'
      else
        message = 'Report has been successfully updated!'
        redirect_to report_path(@report), notice: message
      end
    else
      render action: 'show'
    end
  end

  def sign
    if @report.update(signed: true)
      message = 'Report has been successfully signed!'
      redirect_to report_path(@report), notice: message
    else
      render action: 'show'
    end
  end

  def export
    week_begin_and_end
    render xlsx: 'export', template: 'exports/timesheet'
  end

  private

  def report_params
    params.require(:report)
          .permit(:id, :user_id, :week_id, hours_attributes:
            %i[id category_id sunday monday tuesday wednesday
               thursday friday saturday])
  end

  def set_report
    @report = Report.find(params[:id])
    return if @report.user == current_user || current_user.admin

    flash[:alert] = 'Access denied!'
    redirect_to reports_path
  end

  def week_begin_and_end(today = nil)
    that = @report.created_at
    d = today ? Time.zone.today : Date.new(that.year, that.month, that.day)
    @week_begin = d.beginning_of_week(:sunday).strftime('%m/%d/%Y')
    @week_end   = d.end_of_week(:sunday).strftime('%m/%d/%Y')
  end

  def current_week
    # %U - Week number of the year. The week starts with Sunday. (00..53)
    # %W - Week number of the year. The week starts with Monday. (00..53)
    Time.zone.today.strftime('%U').to_i
  end
end

app/views/reports/_head.html.haml
%center
  %h2
    %b Reports
.row
  .col-md-3
  .col-md-3
  .col-md-3
  .col-md-3
    = form_tag(reports_search_path, method: "post") do
      .form-group
        = label_tag(:date_custom, "Previous reports (custom date): ")
        #datetimepicker1.input-group.date
          = text_field_tag(:date_custom, nil, class: "form-control")
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        :javascript
          $(function () {
              $("#datetimepicker1").datepicker({
               daysOfWeekDisabled: "1,2,3,4,5,6",
               calendarWeeks: true,
               todayHighlight: true,
               toggleActive: true
              });
          });
        %div{:align => "right"}= submit_tag("Search", class: "btn btn-success")

app/views/reports/locked.html.haml
.container
  = render partial: "head"
  %table.tg{:style => "undefined;table-layout: fixed; width: 1068px"}
    = render partial: "reports/timesheet/main"
    = render partial: "reports/timesheet/categories_locked"
    = render partial: "reports/timesheet/signature_and_total"
  %hr
  %div{:align => "right"}
    = "This timesheet is locked, the editing period has expired."
    %br/
    = link_to "Export", timesheet_export_path(@report, format: :xlsx), class: "btn btn-primary" if @report.signed == true
    = link_to "Sign document", sign_report_path(@report), class: "btn btn-primary" if @report.signed == false

app/views/reports/new.html.haml
.container
  = render partial: "head"
  = render partial: "reports/timesheet/js_calc_total"
  = simple_form_for @report do |f|
    %table.tg{:style => "undefined;table-layout: fixed; width: 1068px"}
      = render partial: "reports/timesheet/main"
      = render partial: "reports/timesheet/categories", locals: {f: f}
      = render partial: "reports/timesheet/signature_and_total"
    %hr
    %div{:align => "right"}
      = f.button :submit, "Create report", class: "btn btn-success"

app/views/reports/show.html.haml
.container
  = render partial: "head"
  = render partial: "reports/timesheet/js_calc_total"
  = simple_form_for @report, :method => :patch do |f|
    %table.tg{:style => "undefined;table-layout: fixed; width: 1068px"}
      = render partial: "reports/timesheet/main"
      = render partial: "reports/timesheet/categories", locals: {f: f}
      = render partial: "reports/timesheet/signature_and_total"
    %hr
    %div{:align => "right"}
      = f.button :submit, "Export", class: "btn btn-primary" if @report.signed == true
      = f.button :submit, "Submit", class: "btn btn-success" if @report.signed == true
      = f.button :submit, "Sign and Submit", class: "btn btn-success" if @report.signed == false