config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'reports#index'

  devise_for :users
  authenticated :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users
  resources :teams
  resources :categories

  get 'stats' => 'stats#index'
  get 'stats/user'     => 'stats#user'
  get 'stats/team'     => 'stats#team'
  get 'stats/category' => 'stats#category'
  get 'stats/all'      => 'stats#all'

  post 'stat_reports/user'     => 'stat_reports#user'
  post 'stat_reports/team'     => 'stat_reports#team'
  post 'stat_reports/category' => 'stat_reports#category'
  post 'stat_reports/all'      => 'stat_reports#all'

  post 'exports/stat' => 'exports#stat'

  resources :reports
  get  'reports/:id/sign'   => 'reports#sign',   :as => :sign_report
  get  'reports/:id/export' => 'reports#export', :as => :timesheet_export
  post 'reports/search'     => 'reports#search'

  match '*path', to: 'application#not_found', via: :all
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Time Tracking
    = stylesheet_link_tag 'application', media: :all
    = javascript_include_tag 'application'
  %body
    .nav.navbar.navbar-default{role: 'navigation'}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{type: "button", data: {toggle: 'collapse', target: '#bs-example-navbar-collapse-1' } }
            %span.sr-only Toggle navigation
            %span.icon-ba
            %span.icon-ba
            %span.icon-ba
          %a.navbar-brand{href: '/'} Time Tracking
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          %ul.nav.navbar-nav
            - if current_user
              - if current_user.admin?
                = menu_link 'Users', users_path
                = menu_link 'Teams', teams_path
                = menu_link 'Categories', categories_path
              = menu_link 'Reports', reports_path
              = menu_link 'Stats', stats_path if current_user.admin?
              = menu_link 'Log out', destroy_user_session_path, false, method: :delete
              %li
                = menu_link "Logged in as #{current_user.email}", user_path(current_user)
            - else
              %li.dropdown
                = link_to 'Sign/Log in<b class="caret"></b>'.html_safe, '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown'
                %ul.dropdown-menu
                  = menu_link 'Log in', new_user_session_path
                  -# = menu_link 'Sign up', new_user_registration_path, false
    - flash.each do |name, msg|
      %div{class: "alert alert-#{name == 'notice' ? "success" : "error"}"}
        %a.close{'data-dismiss' => "alert"} &#215;
        = content_tag :div, msg, :id => "flash_#{name}"
    = yield